--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: discountservice
    version: v1
  name: discountservice
spec: 
  strategy: # Default, so usually not specified
    type: discountservice
    rollingUpdate:
      maxSurge: 1  # specifies the maximum number of Pods that can be created over the desired number of Pods
      maxUnavailable: 25% #specifies the maximum number of Pods that can be unavailable during the update process
  replicas: 1
  selector: 
    matchLabels: 
      app: discountservice
      version: v1
  template: 
    metadata: 
      labels: 
        app: discountservice
        version: v1

    spec: 

      containers: 
        - 
          image: "mrinalk84/discountservice-dockerv1:latest"
          imagePullPolicy: Always
          name: apigateway
          ports: 
#          - containerPort: 8081   
          - name: httpport
            containerPort: 8200
            hostPort: 8200 
  

              
                    