--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: apigateway
    version: v1
  name: apigateway
spec: 
  ports: 
    - 
      name: http
      port: 8085
      targetPort: 8085

  selector: 
    app: apigateway
    version: v1
  type: NodePort