--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: productservice
    version: v1
  name: productservice
spec: 
  strategy: # Default, so usually not specified
    type: productservice
    rollingUpdate:
      maxSurge: 1  # specifies the maximum number of Pods that can be created over the desired number of Pods
      maxUnavailable: 25% #specifies the maximum number of Pods that can be unavailable during the update process
  replicas: 1
  selector: 
    matchLabels: 
      app: productservice
      version: v1
  template: 
    metadata: 
      labels: 
        app: productservice
        version: v1

    spec: 

      containers: 
        - 
          image: "mrinalk84/productservice-dockerv1:latest"
          imagePullPolicy: Always
          name: apigateway
          ports: 
#          - containerPort: 8081   
          - name: httpport
            containerPort: 8300
            hostPort: 8300 
  

              
                    