--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: productservice
    version: v1
  name: productservice
spec: 
  ports: 
    - 
      name: http
      port: 8300
      targetPort: 8300

  selector: 
    app: productservice
    version: v1
  type: NodePort