server:
  port: 8100
 
 
spring:
  rabbitmq:
    host: ${rabbitmq.host:192.168.99.100}
    port: ${rabbitmq.port:5672}
    username: guest
    password: guest
    
  zipkin:
    base-url: ${zipkin.url:http://192.168.99.100:9411/}
    
  sleuth:
    sampler:
      probability: 1.0
    trace-id128: true