DROP TABLE IF EXISTS TAX;  
CREATE TABLE TAX (  
	ID NUMBER AUTO_INCREMENT  PRIMARY KEY,  
	PRODUCT_NAME VARCHAR(50) NOT NULL,  
	TAX DOUBLE NOT NULL  
);  
INSERT INTO TAX (PRODUCT_NAME, TAX) VALUES ('Orange', 8.5);  
INSERT INTO TAX (PRODUCT_NAME, TAX) VALUES ('Banana', 10.5);  
INSERT INTO TAX (PRODUCT_NAME, TAX) VALUES ('Apple', 15.0); 