--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: eurekaserver
    version: v1
  name: eurekaserver
spec: 
  strategy: # Default, so usually not specified
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1  # specifies the maximum number of Pods that can be created over the desired number of Pods
      maxUnavailable: 25% #specifies the maximum number of Pods that can be unavailable during the update process
  replicas: 1
  selector: 
    matchLabels: 
      app: eurekaserver
      version: v1
  template: 
    metadata: 
      labels: 
        app: eurekaserver
        version: v1

    spec: 

      containers: 
        - 
          image: "mrinalk84/urekaserver-dockerv1"
          imagePullPolicy: Always
          name: eurekaserver
          ports: 
#          - containerPort: 8081   
          - name: httpport
            containerPort: 8090
            hostPort: 8090      
  

              
                    